### ISSUE TITLE
'tile_shape' - unused CLI argument?

### ISSUE THREAD

**Issue by jjhbw** [TissueImageAnalytics/cerberus#1]
Hi all, congrats on your impressive work!

I'm trying to figure out the dimensions of the input tiles (in microns, not pixels) to feed to the tile inference script. In other words: how much tissue should I feed it?

I assume `run_infer_tile.py` expects a square tissue patch at 0.5 MPP of arbitrary pixel dimension as long as it is divisible by 448, is that correct?

I came across the below CLI argument, but a quick repo-wide search on github suggests it is unused in the rest of the codebase, so I'm a bit confused.

https://github.com/TissueImageAnalytics/cerberus/blob/445837633c83174fea21adaca3cc1eddef0acdee/run_infer_tile.py#L18

**Comment by simongraham** [comment]
Hi @jjhbw 

First of all, I apologise for the delay in getting back to you. I am currently taking a 2 month leave and so am pretty slow dealing with these queries at the moment. You can feed any size input image for tile processing, as long as it is larger than the input patch size, which should be 448x448. `tile_shape` was incorrectly copied over from wsi processing mode and therefore this command line argument is redundant. 

In wsi processing mode, the wsi is broken up into large tiles for more efficient processing, hence this argument.

I will fix this in the repo asap.

**Comment by simongraham** [comment]
This has now been addressed in the above merged PR.
