### ISSUE TITLE
Zip files with model weights is wroken 

### ISSUE THREAD

**Issue by Peregalli** [TissueImageAnalytics/cerberus#18]
I'm trying to run the code but when I download model weights from [this](https://warwick.ac.uk/fac/cross_fac/tia/software/cerberus/resnet34_cerberus.zip) link and unzip the file, .zip file seems to be broken.

**Comment by Peregalli** [comment]
I tried with Ubuntu 22.04 and 20.04 and the same error appears but it works with WIndows (Magic Mike).

**Comment by simongraham** [comment]
Glad that it is now working for you.
