### ISSUE TITLE
Lizard Dataset

### ISSUE THREAD

**Issue by PabloMeseguerEsbri** [TissueImageAnalytics/cerberus#30]
Where can I download the Lizard dataset? Warwick University website is asking for registration... 

Paper --> Lizard: A Large-Scale Dataset for Colonic Nuclear Instance Segmentation and Classification

**Comment by YOOHYOJEONG** [comment]
Hi, I found Lizrd Dataset at kaggle. I hope it helps.

https://www.kaggle.com/datasets/aadimator/lizard-dataset

**Comment by PabloMeseguerEsbri** [comment]
Thank you very much!

**Comment by FabianHoerst** [comment]
Hi @PabloMeseguerEsbri  and @YOOHYOJEONG, do you also have the split information available, meaning which folds should be used for train, validation and testing?

**Comment by windygoo** [comment]
> Hi @PabloMeseguerEsbri and @YOOHYOJEONG, do you also have the split information available, meaning which folds should be used for train, validation and testing?



> Hi @PabloMeseguerEsbri and @YOOHYOJEONG, do you also have the split information available, meaning which folds should be used for train, validation and testing?

Hi, have you got the data split information ?

**Comment by windygoo** [comment]
> > Hi @PabloMeseguerEsbri and @YOOHYOJEONG, do you also have the split information available, meaning which folds should be used for train, validation and testing?
> 
> Hi, have you got the data split information ?
