### ISSUE TITLE
Questions about train_step input

### ISSUE THREAD

**Issue by YOOHYOJEONG** [TissueImageAnalytics/cerberus#31]
Hi. I am a student who was impressed with your works.
Thank you for sharing the inference code. Thanks to you, I was able to infer easily.   
   
I became very interested in your research.
Therefore, I want to not only inference but also training by myself.
I just found the "train_step" function in the code "run_desc.py" among the codes you shared. I tried to train using it but failed because I couldn't figure out what the input data was.

Could you tell me what "dummy_target" is among the contents of batch_data? Also curious what "Branch etc" is.   

And what type of file should "run_info", one of the input data of the "train_step" function, be?
I couldn't find any related files anywhere.   
   
![image](https://github.com/TissueImageAnalytics/cerberus/assets/86641457/74ab1a10-cc28-4ebc-9a0b-0584fe501b1c)
   

You said you don't plan to release the learning code, but can you answer my question?

Thank you.

**Comment by simongraham** [comment]
Apologies, but we do not support training code as part of this repository
