### ISSUE TITLE
Human-in-the-loop Segmentation

### ISSUE THREAD

**Issue by FabianHoerst** [TissueImageAnalytics/cerberus#5]
Hello!

First of all, thank you very much for providing the code. Your paper is very interesting and covers a tremendous range of topics. However, I have a question about section 3.4 (Collecting large datasets for segmentation): Which Tool did you use for performing active learning? Did you implemented it on your own specifically for WSIs or did you used software designed for any type of images, since you are working patch-wise?

Thanks in advance!

**Comment by simongraham** [comment]
Hi @FabianHoerst 

Thanks for the kind words! For the pathologist-in-the-loop annotation process, we generated the segmentation results after each step and refined them using GIMP. Then, we fed re-extracted patches from the refined annotations and retrained each time. Using an integrated interface for this would have been ideal, but we didn't have one in mind.
