### ISSUE TITLE
--cache-path seems hardcoded

### ISSUE THREAD

**Issue by jjhbw** [TissueImageAnalytics/cerberus#6]
Hi! It seems like the below line overrides any setting that the user may have provided for `--cache-path`. I don't think that is intentional, right?

https://github.com/TissueImageAnalytics/cerberus/blob/445837633c83174fea21adaca3cc1eddef0acdee/run_infer_wsi.py#L52

**Comment by simongraham** [comment]
Nice spot. Let me make a PR for this now.

**Comment by simongraham** [comment]
Dealt with in this [merge](https://github.com/TissueImageAnalytics/cerberus/commit/53a3f50e26bfdbb2c1220df16dc2b3f6f0d64e6e).
