### ISSUE TITLE
TypeError: merge_prediction() takes from 3 to 5 positional arguments but 6 were given

### ISSUE THREAD

**Issue by jjhbw** [TissueImageAnalytics/cerberus#8]
I think this is due to `NucleusInstanceSegmentor.merge_prediction(...)` having 5 arguments while 6 are being provided.

https://github.com/TissueImageAnalytics/cerberus/blob/445837633c83174fea21adaca3cc1eddef0acdee/infer/wsi.py#L450-L466

And the code for `NucleusInstanceSegmentor.merge_prediction`:
https://github.com/TissueImageAnalytics/tiatoolbox/blob/73f9d1f4372e8b680ef636de95c8589fa4e8d61a/tiatoolbox/models/engine/semantic_segmentor.py#L859-L864

**Comment by simongraham** [comment]
This will be due to an older version of TIAToolbox using the `free_prediction` argument. I must not have synced the repo with the most up-to-date TIAToolbox. I am now bumping up the dependency to `tiatoolbox==1.3.1`.

**Comment by simongraham** [comment]
The above PR solves the issue - thanks for reporting!
