### ISSUE TITLE
HoVerNet._get_instance_info() signature seems to have changed in TIAToolbox

### ISSUE THREAD

**Issue by jjhbw** [TissueImageAnalytics/cerberus#9]
https://github.com/TissueImageAnalytics/cerberus/blob/445837633c83174fea21adaca3cc1eddef0acdee/infer/wsi.py#L149

The TIAToolbox code has a slightly different method name: https://github.com/TissueImageAnalytics/tiatoolbox/blob/b2556dd30694ff8840c2ebee7efffa337cdeaeb4/tiatoolbox/models/architecture/hovernet.py#L584

**Comment by jjhbw** [comment]
This leads to a fatal error by the way.

```
cerberus/infer/wsi.py", line 149, in _process_tile_predictions
    inst_dict = HoVerNet._get_instance_info(inst_map, type_map)
AttributeError: type object 'HoVerNet' has no attribute '_get_instance_info'
```

**Comment by simongraham** [comment]
Really appreciate the feedback on here - a lot of people would fix the errors without reporting back :)

All is now dealt with. That should have ironed out the issues.
